name: Take snapshot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * 5'

jobs:
  build:
    runs-on: macOS-latest

    strategy:
        matrix:
          node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
    - name: Update README
      run: |-
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_local('.')"
        Rscript -e "remotes::install_cran('usethis')"
        Rscript -e "source(\"R/scrape_data.R\")"
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@example.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Get data: ${{ steps.date.outputs.date }}" -a || echo "No changes to commit"
        git push
